/*---------------------------------------------------------------------
**   Programmer:user_name
**   Date:08/09/25             
**   12D Model:            Vversion
**   Version:              001
**   Macro Name:           TEST.4DM
**   Type:                 SOURCE
**
**   Brief description: BriefDescription
**
**
**---------------------------------------------------------------------
**   Description: Description
**
**
**---------------------------------------------------------------------
**   Update/Modification
**
**
**   (C) Copyright 2013-2025 by your_company Pty Ltd. All Rights
**       Reserved.
**   This macro, or parts thereof, may not be reproduced in any form
**   without permission of your_company.
**---------------------------------------------------------------------
*/
#define DEBUG_FILE      0
#define ECHO_DEBUG_FILE 0
#define ECHO_LINE_NO    0
 
#define BUILD "version.0.001"
 
// ----------------------------- INCLUDES -----------------------------
#include "..\\..\\include\standard_library.H"
#include "..\\..\\include\size_of.H"
/*global variables*/{


}
void main(){

    
}